import React,{useEffect,useMemo,useRef,useState} from 'react'
import * as THREE from 'three'
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js'
import {Icon} from '@iconify/react'
export type ThreeStone={id:number;kind:number;x:number;y:number;layer:number}
export type ThreeWorld={bg:string;icons:readonly string[];colors:readonly string[];table:string;accent:string}
type Props={stones:ThreeStone[];tray:ThreeStone[];theme:ThreeWorld;selectedId:number|null;fx:number;onPick:(s:ThreeStone)=>void}
const iconName=(n:string)=>`game-icons:${n}`
const tileSize=1.12,gap=.98,zFor=(y:number)=>3-y*.92,spread=(l:number)=>Math.max(.58,1-l*.085)
const pos=(s:ThreeStone)=>{const q=spread(s.layer);return new THREE.Vector3((s.x-3)*gap*q,.52+s.layer*.38,zFor(s.y)*q)}
const tileColor=(w:string)=>({orchard:'#ead7b4',nature:'#e3d0a8',crystal:'#dce8ec',magic:'#e1d2bd',space:'#d9e0e9',friends:'#ead7bf',ancient:'#d5c09a',season:'#dfd5bd',collection:'#e1ca9a'} as Record<string,string>)[w]||'#ead7b4'
const grassColor=(w:string)=>({orchard:'#356b3b',nature:'#2f6938',crystal:'#294b59',magic:'#3d2850',space:'#1b3150',friends:'#4d3b30',ancient:'#55402a',season:'#40566a',collection:'#584020'} as Record<string,string>)[w]||'#356b3b'
export default function ThreeBoard({stones,tray,theme,selectedId,fx,onPick}:Props){
 const mount=useRef<HTMLDivElement>(null),sceneRef=useRef<THREE.Scene|null>(null),raf=useRef(0),burstRef=useRef<THREE.Group|null>(null),meshRef=useRef(new Map<number,THREE.Mesh>()),[points,setPoints]=useState<Record<number,{x:number;y:number;z:number;scale:number}>>({})
 const accent=useMemo(()=>new THREE.Color(theme.accent),[theme.accent])
 useEffect(()=>{const el=mount.current;if(!el)return;const scene=new THREE.Scene();sceneRef.current=scene;const camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(0,6.35,8.15)
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0,0);el.appendChild(renderer.domElement)
  const hemi=new THREE.HemisphereLight(0xfff5df,0x17261d,2.25);scene.add(hemi);const key=new THREE.DirectionalLight(0xfff2cf,3.9);key.position.set(-5,10,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);const fill=new THREE.PointLight(accent,4.5,18);fill.position.set(3,4,-4);scene.add(fill)
  const base=new THREE.Mesh(new RoundedBoxGeometry(11.5,1.05,10.8,8,.42),new THREE.MeshStandardMaterial({color:theme.table,roughness:.82,metalness:.03}));base.position.y=-.82;base.receiveShadow=true;base.castShadow=true;scene.add(base)
  const grass=new THREE.Mesh(new RoundedBoxGeometry(10.85,.34,10.15,8,.2),new THREE.MeshStandardMaterial({color:grassColor(theme.bg),roughness:1}));grass.position.y=-.2;grass.receiveShadow=true;scene.add(grass)
  const inner=new THREE.Mesh(new RoundedBoxGeometry(9.9,.16,9.15,8,.16),new THREE.MeshStandardMaterial({color:new THREE.Color(theme.table).multiplyScalar(.65),roughness:.62}));inner.position.y=-.02;scene.add(inner)
  const rim=new THREE.Mesh(new RoundedBoxGeometry(10.3,.28,9.5,8,.22),new THREE.MeshStandardMaterial({color:theme.accent,roughness:.3,metalness:.4,transparent:true,opacity:.48}));rim.position.y=.08;scene.add(rim)
  for(let i=0;i<16;i++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.16+(i%3)*.025,7,7),new THREE.MeshStandardMaterial({color:['#214d2d','#2d6937','#438044','#173e28'][i%4],roughness:1}));leaf.scale.set(1.6,.45,.8);leaf.position.set(((i*43)%100)/100*9.7-4.85,.1,((i*67)%100)/100*8.5-4.25);scene.add(leaf)}
  for(let i=0;i<10;i++){const glow=new THREE.Mesh(new THREE.SphereGeometry(.055,8,8),new THREE.MeshBasicMaterial({color:0xffe6a0,transparent:true,opacity:.85}));glow.position.set(((i*71)%100)/100*9-4.5,.45+((i*17)%5)*.12,((i*29)%100)/100*7.5-3.75);scene.add(glow)}
  const trayBase=new THREE.Mesh(new RoundedBoxGeometry(8.6,.38,1.65,6,.22),new THREE.MeshStandardMaterial({color:0x3a291b,roughness:.45,metalness:.2}));trayBase.position.set(0,.22,4.35);trayBase.castShadow=true;scene.add(trayBase);for(let i=0;i<7;i++){const slot=new THREE.Mesh(new RoundedBoxGeometry(.92,.13,1.15,5,.12),new THREE.MeshStandardMaterial({color:0x17151a,roughness:.5}));slot.position.set((i-3)*1.05,.43,4.35);scene.add(slot)}
  const burst=new THREE.Group();burstRef.current=burst;scene.add(burst);let px=0,pz=0,frame=0;const pointer=(e:PointerEvent)=>{const r=el.getBoundingClientRect();px=(e.clientX-r.left)/r.width*2-1;pz=(e.clientY-r.top)/r.height*2-1};el.addEventListener('pointermove',pointer)
  const resize=()=>{const w=el.clientWidth||320,h=el.clientHeight||560;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};resize();const ro=new ResizeObserver(resize);ro.observe(el)
  const tick=()=>{raf.current=requestAnimationFrame(tick);frame++;const now=performance.now()/1000;camera.position.x+=(px*.42-camera.position.x)*.035;camera.position.z+=(8.15+pz*.22-camera.position.z)*.035;camera.lookAt(0,.85,.15);meshRef.current.forEach(m=>{const target=m.userData.flightTarget as THREE.Vector3|undefined;if(m.userData.selected&&target){m.position.lerp(target,.14);m.rotation.y+=.06;m.rotation.z=Math.sin(now*11)*.07}else m.rotation.y+=(Math.sin(now+m.userData.phase)*.002-m.rotation.y)*.08});burst.children.forEach(c=>{const p=c as THREE.Mesh,v=p.userData.v as THREE.Vector3;p.position.add(v);v.y-=.006;(p.material as THREE.MeshBasicMaterial).opacity*=.965});renderer.render(scene,camera);if(frame%2===0){const next:Record<number,{x:number;y:number;z:number;scale:number}>={};meshRef.current.forEach((m,id)=>{const p=m.position.clone().add(new THREE.Vector3(0,.15,0));p.project(camera);const r=renderer.domElement.getBoundingClientRect();next[id]={x:(p.x*.5+.5)*r.width,y:(-p.y*.5+.5)*r.height,z:p.z,scale:Math.max(.78,Math.min(1.2,11.5/(m.position.distanceTo(camera.position)+.01)))}});setPoints(next)}};tick()
  return()=>{cancelAnimationFrame(raf.current);el.removeEventListener('pointermove',pointer);ro.disconnect();renderer.dispose();if(renderer.domElement.parentElement===el)el.removeChild(renderer.domElement);scene.clear();meshRef.current.clear()}
 },[theme.table,theme.accent,theme.bg,accent])
 useEffect(()=>{const scene=sceneRef.current;if(!scene)return;[...meshRef.current.values()].forEach(m=>{scene.remove(m);m.geometry.dispose();(m.material as THREE.Material).dispose()});meshRef.current.clear();stones.forEach((s,i)=>{const geo=new RoundedBoxGeometry(tileSize,.5,tileSize,7,.17),mat=new THREE.MeshStandardMaterial({color:tileColor(theme.bg),roughness:.34,metalness:.04}),m=new THREE.Mesh(geo,mat);m.position.copy(pos(s));m.castShadow=true;m.receiveShadow=true;m.rotation.y=(s.id%9)*.045;m.userData={id:s.id,selected:s.id===selectedId,phase:i*.31};scene.add(m);meshRef.current.set(s.id,m)})},[stones,selectedId,theme.bg])
 useEffect(()=>{meshRef.current.forEach((m,id)=>{m.userData.selected=id===selectedId;if(id===selectedId)m.userData.flightTarget=new THREE.Vector3((tray.length-3)*1.05,.95,4.35);else delete m.userData.flightTarget})},[selectedId,tray.length])
 useEffect(()=>{const group=burstRef.current;if(!group||!fx)return;group.clear();for(let i=0;i<44;i++){const a=i/44*Math.PI*2,g=new THREE.SphereGeometry(.035+Math.random()*.06,5,5),m=new THREE.MeshBasicMaterial({color:accent,transparent:true,opacity:1}),p=new THREE.Mesh(g,m);p.position.set((Math.random()-.5)*.5,1+(Math.random()-.5)*.3,(Math.random()-.5)*.5);p.userData.v=new THREE.Vector3(Math.cos(a)*(.05+Math.random()*.14),.04+Math.random()*.12,Math.sin(a)*(.05+Math.random()*.14));group.add(p)}const timer=window.setTimeout(()=>group.clear(),780);return()=>clearTimeout(timer)},[fx,accent])
 const overlays=stones.map(s=>{const p=points[s.id];if(!p)return null;const blocked=stones.some(o=>o.id!==s.id&&o.layer>s.layer&&Math.abs(o.x-s.x)<=1&&Math.abs(o.y-s.y)<=1);return <button key={s.id} className={`three-icon-button ${blocked?'blocked':''} ${selectedId===s.id?'picked':''}`} style={{left:p.x,top:p.y,transform:`translate(-50%,-50%) scale(${p.scale})`,zIndex:Math.round((1-p.z)*1000)}} disabled={blocked||selectedId!==null} onClick={()=>onPick(s)}><Icon icon={iconName(theme.icons[s.kind%theme.icons.length])} style={{color:iconTint(theme.icons[s.kind%theme.icons.length])}}/></button>})
 const trayIcons=tray.map((s,i)=><div key={s.id} className="three-tray-icon" style={{left:`calc(50% + ${(i-3)*1.05/8.6*100}%)`}}><Icon icon={iconName(theme.icons[s.kind%theme.icons.length])} style={{color:iconTint(theme.icons[s.kind%theme.icons.length])}}/></div>)
 return <div className={`three-board world-${theme.bg}`}><div ref={mount} className="three-canvas"/><div className="three-overlays">{overlays}</div><div className="three-tray-overlays">{trayIcons}</div><div className="three-depth-glow"/></div>
}