import React,{useEffect,useMemo,useRef,useState} from 'react'
import * as THREE from 'three'
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js'
import {Icon} from '@iconify/react'
export type ThreeStone={id:number;kind:number;x:number;y:number;layer:number}
export type ThreeWorld={bg:string;icons:readonly string[];colors:readonly string[];table:string;accent:string}
type Props={stones:ThreeStone[];tray:ThreeStone[];theme:ThreeWorld;selectedId:number|null;fx:number;onPick:(s:ThreeStone)=>void}
const iconName=(name:string)=>`game-icons:${name}`
const tileSize=1.08,gap=1.0,boardZ=(y:number)=>3.0-y*.92
const tileMaterial=(bg:string)=>new THREE.Color(bg==='crystal'?'#d9e7ef':bg==='magic'?'#dfd0ba':bg==='space'?'#d8dde7':bg==='ancient'?'#d6c2a1':bg==='friends'?'#ead4bd':'#ead8b8')
const bgGrass=(bg:string)=>bg==='crystal'?'#284b52':bg==='magic'?'#3b274a':bg==='space'?'#1b2d4b':bg==='ancient'?'#4b3826':bg==='friends'?'#4b392d':'#315b35'
const bgLeaf=(i:number)=>['#1e5a39','#2e7242','#3c8045','#1b492f'][i%4]
const layerSpread=(layer:number)=>layer===0?1:layer===1?.86:layer===2?.68:.52
const pos=(s:ThreeStone)=>{const spread=layerSpread(s.layer);return new THREE.Vector3((s.x-3)*gap*spread,.58+s.layer*.34,boardZ(s.y)*gap*spread)}
export default function ThreeBoard({stones,tray,theme,selectedId,fx,onPick}:Props){
 const mount=useRef<HTMLDivElement>(null),sceneRef=useRef<THREE.Scene|null>(null),cameraRef=useRef<THREE.PerspectiveCamera|null>(null),raf=useRef(0),burstRef=useRef<THREE.Group|null>(null),meshRef=useRef(new Map<number,THREE.Mesh>()),[points,setPoints]=useState<Record<number,{x:number;y:number;z:number;scale:number}>>({})
 const worldColors=useMemo(()=>theme.colors.map(v=>new THREE.Color(v)),[theme.colors])
 useEffect(()=>{const el=mount.current;if(!el)return;const scene=new THREE.Scene();scene.background=null;sceneRef.current=scene;const camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,7.45,9.7);cameraRef.current=camera;const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0x000000,0);el.appendChild(renderer.domElement)
 const hemi=new THREE.HemisphereLight(0xffffff,0x263044,2.1);scene.add(hemi);const key=new THREE.DirectionalLight(0xffffff,3.5);key.position.set(-4,10,7);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-10;key.shadow.camera.right=10;key.shadow.camera.top=10;key.shadow.camera.bottom=-10;scene.add(key);const rim=new THREE.PointLight(new THREE.Color(theme.accent),5,18);rim.position.set(5,4,-5);scene.add(rim)
 const base=new THREE.Mesh(new RoundedBoxGeometry(11.5,1.15,10.9,8,.42),new THREE.MeshStandardMaterial({color:new THREE.Color(theme.table),roughness:.8,metalness:.04}));base.position.y=-.82;base.receiveShadow=true;base.castShadow=true;scene.add(base);const foliage=new THREE.Mesh(new RoundedBoxGeometry(10.95,.35,10.35,8,.22),new THREE.MeshStandardMaterial({color:bgGrass(theme.bg),roughness:1,metalness:0}));foliage.position.y=-.18;foliage.receiveShadow=true;scene.add(foliage);const inlay=new THREE.Mesh(new RoundedBoxGeometry(10.2,.2,9.35,8,.2),new THREE.MeshStandardMaterial({color:new THREE.Color(theme.table).multiplyScalar(.62),roughness:.5,metalness:.1}));inlay.position.y=.02;inlay.receiveShadow=true;scene.add(inlay);const frame=new THREE.Mesh(new RoundedBoxGeometry(10.45,.32,9.65,8,.24),new THREE.MeshStandardMaterial({color:new THREE.Color(theme.accent),roughness:.3,metalness:.38,transparent:true,opacity:.48}));frame.position.y=.07;scene.add(frame);for(let i=0;i<20;i++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.18+((i*11)%6)/100,7,7),new THREE.MeshStandardMaterial({color:bgLeaf(i),roughness:1}));leaf.scale.set(1.4,.45,.72);leaf.position.set(((i*37)%100)/100*10-5,.08,((i*61)%100)/100*8.9-4.45);leaf.castShadow=true;scene.add(leaf)}
 const trayBase=new THREE.Mesh(new RoundedBoxGeometry(8.5,.38,1.65,5,.22),new THREE.MeshStandardMaterial({color:0x111522,roughness:.38,metalness:.28}));trayBase.position.set(0,.16,4.7);trayBase.receiveShadow=true;trayBase.castShadow=true;scene.add(trayBase);for(let i=0;i<7;i++){const slot=new THREE.Mesh(new RoundedBoxGeometry(.9,.12,1.15,4,.12),new THREE.MeshStandardMaterial({color:0x252b3c,roughness:.55,metalness:.15}));slot.position.set((i-3)*1.05,.38,4.7);scene.add(slot)}
 const burst=new THREE.Group();burstRef.current=burst;scene.add(burst);let px=0,pz=0;const pointer=(e:PointerEvent)=>{const r=el.getBoundingClientRect();px=(e.clientX-r.left)/r.width*2-1;pz=(e.clientY-r.top)/r.height*2-1};el.addEventListener('pointermove',pointer);const resize=()=>{const w=el.clientWidth||320,h=el.clientHeight||560;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};resize();const ro=new ResizeObserver(resize);ro.observe(el)
 const tick=()=>{raf.current=requestAnimationFrame(tick);const now=performance.now()/1000;camera.position.x+=(px*.75-camera.position.x)*.035;camera.position.z+=(10.2+pz*.45-camera.position.z)*.035;camera.lookAt(0,.65,.35);meshRef.current.forEach(m=>{const selected=m.userData.selected as boolean,target=m.userData.flightTarget as THREE.Vector3|undefined;if(selected&&target){m.position.lerp(target,.13);m.rotation.y+=.055;m.rotation.z=Math.sin(now*10)*.06}else if(!selected)m.rotation.y+=(Math.sin(now+m.userData.phase)*.0015-m.rotation.y)*.08});burst.children.forEach(child=>{const p=child as THREE.Mesh;const v=p.userData.v as THREE.Vector3;p.position.add(v);v.y-=.006;(p.material as THREE.MeshBasicMaterial).opacity*=.965});renderer.render(scene,camera);const next:Record<number,{x:number;y:number;z:number;scale:number}>={};meshRef.current.forEach((m,id)=>{const p=m.position.clone().add(new THREE.Vector3(0,.12,0));p.project(camera);const r=renderer.domElement.getBoundingClientRect();next[id]={x:(p.x*.5+.5)*r.width,y:(-p.y*.5+.5)*r.height,z:p.z,scale:Math.max(.7,Math.min(1.3,12/(m.position.distanceTo(camera.position)+.01)))}});setPoints(next)};tick();return()=>{cancelAnimationFrame(raf.current);el.removeEventListener('pointermove',pointer);ro.disconnect();renderer.dispose();el.removeChild(renderer.domElement);scene.clear();meshRef.current.clear()}},[theme.table,theme.accent])
 useEffect(()=>{const scene=sceneRef.current;if(!scene)return;const old=[...meshRef.current.values()];old.forEach(m=>{scene.remove(m);m.geometry.dispose();(m.material as THREE.Material).dispose()});meshRef.current.clear();stones.forEach((s,i)=>{const geo=new RoundedBoxGeometry(tileSize,.48,tileSize,7,.16);const mat=new THREE.MeshStandardMaterial({color:tileMaterial(theme.bg),roughness:.34,metalness:.06});const m=new THREE.Mesh(geo,mat);m.position.copy(pos(s));m.castShadow=true;m.receiveShadow=true;m.userData={id:s.id,selected:s.id===selectedId,phase:i*.37,kind:s.kind};m.rotation.y=(s.id%7)*.06;scene.add(m);meshRef.current.set(s.id,m)})},[stones,selectedId,worldColors])
 useEffect(()=>{meshRef.current.forEach((m,id)=>{m.userData.selected=id===selectedId;if(id===selectedId)m.userData.flightTarget=new THREE.Vector3((tray.length-3)*1.05,.95,4.7);else delete m.userData.flightTarget})},[selectedId,tray.length])
 useEffect(()=>{const group=burstRef.current;if(!group||!fx)return;group.clear();for(let i=0;i<36;i++){const a=(i/36)*Math.PI*2,g=new THREE.SphereGeometry(.035+Math.random()*.055,5,5),m=new THREE.MeshBasicMaterial({color:new THREE.Color(theme.accent),transparent:true,opacity:1});const p=new THREE.Mesh(g,m);p.position.set((Math.random()-.5)*.35,1+(Math.random()-.5)*.25,(Math.random()-.5)*.35);p.userData.v=new THREE.Vector3(Math.cos(a)*(.045+Math.random()*.13),.04+Math.random()*.11,Math.sin(a)*(.045+Math.random()*.13));group.add(p)}const timer=window.setTimeout(()=>group.clear(),760);return()=>clearTimeout(timer)},[fx,theme.accent])
 const overlays=stones.map(s=>{const p=points[s.id];if(!p)return null;const blocked=stones.some(o=>o.id!==s.id&&o.layer>s.layer&&Math.abs(o.x-s.x)<=1&&Math.abs(o.y-s.y)<=1);return <button key={s.id} className={`three-icon-button ${blocked?'blocked':''} ${selectedId===s.id?'picked':''}`} style={{left:p.x,top:p.y,transform:`translate(-50%,-50%) scale(${p.scale})`,zIndex:Math.round((1-p.z)*1000)}} disabled={blocked||selectedId!==null} onClick={()=>onPick(s)}><Icon icon={iconName(theme.icons[s.kind%theme.icons.length])}/></button>});const trayIcons=tray.map((s,i)=><div key={s.id} className="three-tray-icon" style={{left:`calc(50% + ${(i-3)*1.05/8.5*100}%)`}}><Icon icon={iconName(theme.icons[s.kind%theme.icons.length])}/></div>);return <div className={`three-board world-${theme.bg}`}><div ref={mount} className="three-canvas"/><div className="three-overlays">{overlays}</div><div className="three-tray-overlays">{trayIcons}</div><div className="three-depth-glow"/></div>}
